### ISSUE TITLE
Problem with Python functions

### ISSUE THREAD

**Issue by narimiran** [yami-beta/asyncomplete-omni.vim#15] opened 2019-09-21 08:16 UTC
Consider the following code:

```python
class Foo:
    def cl_foo(self, b):
        return 3*self + 5*b

def fn_foo(a, b):
    return 3*a + 5*b

f = Foo()
```

Now, if you type `f.cl`, you'll get your completion options and you can easily complete the line to became `f.cl_foo(`. This is a correct and expected behaviour.

Contrast this with typing `fn` and getting completion options. If you choose the `fn_foo(a,b)` option, your line becomes: `_foo(`!
The same behaviour can be observed for the previous example if you left the insert mode after typing `f.`, when you enter insert mode again and continue to type `cl`, your line will be completed to `f._foo(`.

Using `C-x C-o`, instead of automatic completion options, gives correct behaviour in all three examples.

**Comment by yami-beta** [comment] 2019-10-02 21:53
I'm sorry for replying late.

I try it, but the result of completion looks as intended.

![test-python](https://user-images.githubusercontent.com/5106704/66084044-a8c10800-e5a8-11e9-8cbf-8c0f6bb42b20.gif)

Above sample is tried with following minimal vimrc.

```vim
set nocompatible

call plug#begin('~/.vim/plug')
  Plug 'prabirshrestha/asyncomplete.vim'
  Plug '~/dev/src/github.com/yami-beta/asyncomplete-omni.vim'
call plug#end()

call asyncomplete#register_source(asyncomplete#sources#omni#get_source_options({
  \ 'name': 'omni',
  \ 'whitelist': ['*'],
  \ 'completor': function('asyncomplete#sources#omni#completor')
  \  }))
```

Could you show minimal vimrc to reproduce ?

**Comment by narimiran** [comment] 2019-10-03 05:53
> Could you show minimal vimrc to reproduce ?

Thanks for giving me the direction at which I should look. After commenting out more and more parts of my config I finally found the problem: it is only when this plugin is used in combination with https://github.com/prabirshrestha/asyncomplete-buffer.vim

If you want to reproduce the behaviour, I think this would do:

```vim
set nocompatible

call plug#begin('~/.vim/plug')
  Plug 'prabirshrestha/asyncomplete.vim'
  Plug 'prabirshrestha/asyncomplete-buffer.vim' 
  Plug '~/dev/src/github.com/yami-beta/asyncomplete-omni.vim'
call plug#end()

call asyncomplete#register_source(asyncomplete#sources#omni#get_source_options({
  \ 'name': 'omni',
  \ 'whitelist': ['*'],
  \ 'completor': function('asyncomplete#sources#omni#completor')
  \  }))

call asyncomplete#register_source(
    \ asyncomplete#sources#buffer#get_source_options({
    \   'name': 'buffer',
    \   'whitelist': ['*'],
    \   'completor': function('asyncomplete#sources#buffer#completor'),
    \ }))

```

----

I've added `python` to the blacklist of `asyncomplete-buffer` and this did the trick. As far as I'm concerned, this issue can now be closed.

**Comment by yami-beta** [comment] 2019-10-08 13:28
Thank you to survey.

I'll close this issue, but if you find problem feel free to reopen or create a new issue.

**Closed as completed** 2019-10-09 19:33 UTC
